### PR TITLE
Implement open with tiled buttons

### LINKED ISSUE #76: The user would like to open a map with Tiled from Studio
As an **User**
I want **to open a map with Tiled right from Studio**
So that **I can edit it quickly without having to navigate between software and file explorer**

> [!NOTE]
> Use the context menu of a map (right click) to add "Open with Tiled".
> Add a Edition section to the page actions. [See the component on Figma](https://www.figma.com/file/xglOHHLb96zfPMTXd3v8i9/Pok%C3%A9mon-Studio?type=design&node-id=9217-10690&mode=design&t=j3jBSqRFVtg4vmTE-4)

## Acceptance criterias
- [x] The user is able to open a map from Studio
- [x] Tiled starts if it is not already
- [x] Tiled displays the right map
- [ ] If Tiled is not properly installed or if Studio can't open Tiled, display a modal to warn the user and make sure they can go to the app Settings UI related to Tiled and go to the official website to download it or to provide a new Tiled installation path

### PR DESCRIPTION
**Pull request by NuriYuri**
## Description

Fix #76 

This PR has no clue about tiled install because it's handled by another task so for now it just shows an alert and doesn't try to detect if tiled is properly setup

## Tests to perform

1. Open a map, click on open with tiled, it should open tiled on that map
2. Right click on a map, click on open with tiled, it should open tiled on that map

### CODE REVIEW

**Review by AerunDev — APPROVED** [review]
Works perfectly! ✅ 

We just need to add a feedback if Tiled is not installed or can not be found.
We need to see if this code works with Linux & MacOS too or if we need to add a feedback or just make the feature not available in those OS.

**Comment by AerunDev** [comment]
Just in case, I have this error in the console:
image
To reproduce it:
- Open a map with Tiled by using the button or the contextual menu
- Close Tiled once the map has been properly displayed
- Check the console

**Comment by Palbolsky** [comment]
It's a bug with Tiled . There is the same problem with the cmd:
image

**Review by Palbolsky — COMMENTED** [review]
Shouldn't this feature be disabled in RMXP mode?

**Comment by NuriYuri** [comment]
Oui bien sûr mais il y a une tache pour ça: https://github.com/PokemonWorkshop/PokemonStudio/issues/121
(Faites delete + tout ce qui est relatif à tiled en fait).

**Comment by NuriYuri** [comment]
D'ailleurs, je peux pas faire le rebase d'où je suis alors faites le pour corriger le conflit et merge.

**Review by Palbolsky — APPROVED** [review]

**Comment by Palbolsky** [comment]
> D'ailleurs, je peux pas faire le rebase d'où je suis alors faites le pour corriger le conflit et merge.

C'est fait :) Je laisse Aerun merge si c'est bon pour lui.

**Pull request merged**
